import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://kit.fontawesome.com/ae0af40f93.css"
          crossOrigin="anonymous"
        />
        {/* Bootstrap-Icon CDN Link */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css"
        ></link>
      </Head>
      <main className={styles.main}>
        <div className={styles.bg}></div>

        <div className={`${styles.my_self} ${styles.my_self1}`}>
          <h1 className={inter.className} style={{ fontWeight: "800", fontSize: "2rem" }}>Verasit Wisitsophon</h1>
          <i className="cib-evernote"></i>
          <p className={inter.className}>
            I&apos;m <span style={{ color: "blue", fontSize: "2rem" }}>Mobile Developer</span>
          </p>
          <div className={styles.my_social}>
            <Link href="https://github.com/ibiz-alc" rel="noopener noreferrer" target="_blank"><div className={styles.github}></div></Link>
            <Link href="https://www.linkedin.com/in/emanym/" rel="noopener noreferrer" target="_blank"><div className={styles.linkedin}></div></Link>
          </div>
        </div>

        <section className={styles.about}>
        <div className="grid grid-cols-12">
            <div className="col-start-2 col-span-10 mt-10">
            <h1 style={{ marginTop: "5rem" }}>About</h1>
            <p>
            I like to code, like the world of Mobile Application. I love creating cool things and helping people develop awesome things. Also, my main thing is that I am good at building beautiful app interfaces. For me, making useful stuff for people is really important. That&apos;s why I always want to create beautiful user experience using modern technologies for this reason I spend a lot of time learning about it
            </p>

            <div className="grid grid-cols-1 tablet:grid-cols-12 gap-4 mt-6">
              <div className="tablet:col-span-12 laptop:col-span-4">
                <img src="/profile.png" alt='' />
              </div>
              <div className="tablet:col-span-12 laptop:col-span-8">
                <h3 className="tablet:text-center tablet:ml-0 laptop:text-left laptop:ml-24">Mobile Developer</h3>
                <div className="grid grid-cols-6">
                  <div className="col-span-12 laptop:col-start-1 laptop:col-end-3">
                    <ul>
                      <li>
                        <i
                          className={`bi bi-chevron-left ${styles.fill_color}`}
                        />
                        <b>Birthday:</b> 11 December 1991
                      </li>
                      <li>
                        <i className="bi bi-chevron-left" />
                        <b>Degree:</b> bachelor
                      </li>
                      <li>
                        <i className="bi bi-chevron-left" />
                        <b>Phone:</b> 082-328-4664
                      </li>
                    </ul>
                  </div>
                  <div className="col-span-12 laptop:col-end-6 laptop:col-span-3">
                    <ul>
                      <li>
                        <i className="bi bi-chevron-left" />
                        <b>Age:</b> 31
                      </li>
                      <li>
                        <i className="bi bi-chevron-left" />
                        <b>E-mail:</b> vwsp.y.am@gmail.com
                      </li>
                      <li>
                        <i className="bi bi-chevron-left" />
                        <b>City:</b> Nonthaburi
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          </div>
        </section>
        <section className={`${styles.skills}`}>
          <div className="grid grid-cols-12">
            <div className="col-start-2 col-span-10 mt-10">
              <h1>Skill</h1>
              <div className="grid tablet:grid-cols-1 laptop:grid-cols-2 desktop:grid-cols-2 laptop:gap-4 laptop:mt-6">
                <div className="grid grid-cols-1 laptop:mr-4">
                  <div className={styles.progress}>
                    <span className={styles.skill}>
                      Kotlin <i className={styles.val}>95%</i>
                    </span>
                    <div className={styles["progress-bar-wrap"]}>
                      <div
                        className={styles["progress-bar"]}
                        role="progressbar"
                        aria-valuenow={70}
                        aria-valuemin={0}
                        aria-valuemax={100}
                        style={{ width: "95%" }}
                      ></div>
                    </div>
                  </div>
                  <div className={styles.progress}>
                    <span className={styles.skill}>
                      Jetpack Compose <i className={styles.val}>95%</i>
                    </span>
                    <div className={styles["progress-bar-wrap"]}>
                      <div
                        className={styles["progress-bar"]}
                        role="progressbar"
                        aria-valuenow={70}
                        aria-valuemin={0}
                        aria-valuemax={100}
                        style={{ width: "95%" }}
                      ></div>
                    </div>
                  </div>
                  <div className={styles.progress}>
                    <span className={styles.skill}>
                      HTML <i className={styles.val}>100%</i>
                    </span>
                    <div className={styles["progress-bar-wrap"]}>
                      <div
                        className={styles["progress-bar"]}
                        role="progressbar"
                        aria-valuenow={70}
                        aria-valuemin={0}
                        aria-valuemax={100}
                        style={{ width: "100%" }}
                      ></div>
                    </div>
                  </div>
                </div>
                <div className="grid tablet:grid-cols-1 laptop:ml-4">
                  <div className={styles.progress}>
                    <span className={styles.skill}>
                      Flutter <i className={styles.val}>90%</i>
                    </span>
                    <div className={styles["progress-bar-wrap"]}>
                      <div
                        className={styles["progress-bar"]}
                        role="progressbar"
                        aria-valuenow={70}
                        aria-valuemin={0}
                        aria-valuemax={100}
                        style={{ width: "90%" }}
                      ></div>
                    </div>
                  </div>
                  <div className={styles.progress}>
                    <span className={styles.skill}>
                      Swift <i className={styles.val}>60%</i>
                    </span>
                    <div className={styles["progress-bar-wrap"]}>
                      <div
                        className={styles["progress-bar"]}
                        role="progressbar"
                        aria-valuenow={70}
                        aria-valuemin={0}
                        aria-valuemax={100}
                        style={{ width: "50%" }}
                      ></div>
                    </div>
                  </div>
                  <div className={styles.progress}>
                    <span className={styles.skill}>
                      TypeScript <i className={styles.val}>70%</i>
                    </span>
                    <div className={styles["progress-bar-wrap"]}>
                      <div
                        className={styles["progress-bar"]}
                        role="progressbar"
                        aria-valuenow={70}
                        aria-valuemin={0}
                        aria-valuemax={100}
                        style={{ width: "70%" }}
                      ></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.resume}>
          <div>
            <div className="grid grid-cols-12 mt-6">
              <div className="col-start-2 col-span-10 mt-10">
                <h1>Resume</h1>
                <div className="grid tablet:grid-cols-1 laptop:grid-cols-2 gap-4 mt-6">
                  <div
                    className={`${styles["resume-content-summary"]} grid tablet:grid-cols-1 mr-4 self-start`}
                  >
                    <h3 className={styles["resume-title"]}>Sumary</h3>

                    <div
                      className={`${styles["resume-item"]} ${styles["pb-0"]}`}
                    >
                      <h4>Verasit Wisitsophon</h4>
                      <p>
                        <em>
                          10+ years of experience mobile application.
                        </em>
                      </p>
                      <ul>
                        <li>Android Java</li>
                        <li>Kotlin</li>
                        <li>Jetpack Compose</li>
                        <li>Flutter & Dart</li>
                        <li>Swift</li>
                        <li>Python</li>
                        <li>Next.js</li>
                        <li>Node.js</li>
                        <li>React</li>
                      </ul>
                    </div>
                    <h3 className={styles["resume-title"]}>Education</h3>

                    <div className={`${styles["resume-item"]}`}>
                      <h4>Bachelor’s Degree Faculty of Business Administration</h4>
                      <p>
                        <em>
                          Major Information System
                        </em>
                      </p>
                      <ul>
                        <li>Rajamangala University of Technology Krungthep.</li>
                      </ul>
                    </div>
                  </div>
                  <div className="grid grid-cols-1 laptop:ml-4">
                    <h3 className={styles["resume-title"]}>
                      Professional Experience
                    </h3>

                    <div className={`${styles["resume-item1"]}`}>
                      <h4>Lead Android Developer</h4>
                      <h5>2020 - Present</h5>
                      <p>
                        <em>Thaivivat, Bangkok</em>
                      </p>
                      <ul className="list-disc">
                        <li>
                          Lead development team in the design, coaching,
                          development, coding, testing, and debugging of
                          applications to deliver both quality and capacity.
                        </li>
                        <li>
                          Work closely with business units (UI-UX, Manager,
                          Backend) to understand their requirements and provide
                          these in technical terms for the development team.
                        </li>
                        <li>
                          Responsible for the architect, design, and ongoing
                          development configure applications to meet business
                          process and application requirements.
                        </li>
                        <li>
                          Review new and existing codes to identify areas of
                          improvement.
                        </li>
                        <li>Make core library use of team.</li>
                      </ul>
                      <p>
                        <em><b>Kotlin & Jetpack Compose</b></em>
                      </p>
                      <div className={`${styles["image-container"]}`}>
                        <Link href="https://play.google.com/store/apps/details?id=com.thaivivat.superapp" rel="noopener noreferrer" target="_blank"><img src="/tvi.webp" alt="tvi" width={48} height={48} /></Link>
                      </div>
                      <p className='mt-2'>
                        <em><b>Jetpack Compose</b></em>
                      </p>
                      <div className={`${styles["image-container"]}`}>
                        <img src="/claim_app.png" alt="claim_app" width={48} height={48} />
                      </div>
                    </div>

                    <div className={`${styles["resume-item1"]}`}>
                      <h4>Senior Android DEVELOPER</h4>
                      <h5>Jun 2015 - May 2020</h5>
                      <p>
                        <em>Buzzebees, Bangkok</em>
                      </p>
                      <ul className="list-disc">
                        <li>
                          Be a part of an android team, work in cross functional
                          model and agile development.
                        </li>
                        <li>
                          Work on assigned task and review other developers code
                          to ensure code quality.
                        </li>
                        <li>
                          Attend a retrospective meeting to update work progress
                          and problem encountered during the week.
                        </li>
                        <li>Make core library use of team</li>
                      </ul>
                      <p>
                        <em><b>Kotlin & Java, etc.</b></em>
                      </p>
                      <div className={`${styles["image-container"]}`}>
                        <Link href="https://play.google.com/store/apps/details?id=com.samsung.th.galaxyappcenter&hl=en&gl=US" rel="noopener noreferrer" target="_blank"><img src="/galaxy_reward.png" alt="galaxy_reward" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.samsung.privilege&hl=th&gl=US" rel="noopener noreferrer" target="_blank"><img src="/galaxy_gift.png" alt="galaxy_gift" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.truecoffee" rel="noopener noreferrer" target="_blank"><img src="/true.png" alt="true" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=th.co.crie.tron2.android" rel="noopener noreferrer" target="_blank"><img src="/dtac.webp" alt="webp" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.greyhound" rel="noopener noreferrer" target="_blank"><img src="/greyhound.png" alt="greyhound" width={48} height={48} /></Link>
                        <img src="/bzb.png" alt="bzb" width={48} height={48} />
                        <img src="/reward_buzz.png" alt="reward_buzz" width={48} height={48} />
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.beerlao" rel="noopener noreferrer" target="_blank"><img src="/beerlao.png" alt="beerlao" width={48} height={48} /></Link>
                        <Link href="https://apps.apple.com/th/app/healthy-living/id1120542025" rel="noopener noreferrer" target="_blank"><img src="/hl.png" alt="hl" width={48} height={48} /></Link>
                        <img src="/synnex.png" alt="synnex" width={48} height={48} />
                        <img src="/get_van.png" alt="get_van" width={48} height={48} />
                        <img src="/what_sale.png" alt="what_sale" width={48} height={48} />
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.tgfone" rel="noopener noreferrer" target="_blank"><img src="/tg.png" alt="tg" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.blackmores" rel="noopener noreferrer" target="_blank"><img src="/blackmore.png" alt="blackmore" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.mama" rel="noopener noreferrer" target="_blank"><img src="/spc.png" alt="spc" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.mbk" rel="noopener noreferrer" target="_blank"><img src="/mbk.png" alt="mbk" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.megabangna" rel="noopener noreferrer" target="_blank"><img src="/mega_bangna.png" alt="mega_bangna" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.oceanlife" rel="noopener noreferrer" target="_blank"><img src="/ocean_life.png" alt="ocean_life" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.enfa.geniusbaby" rel="noopener noreferrer" target="_blank"><img src="/mj.png" alt="mj" width={48} height={48} /></Link>
                        <img src="/splus.png" alt="splus" width={48} height={48} />
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.royalcanin" rel="noopener noreferrer" target="_blank"><img src="/royal_canin.png" alt="royal_canin" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.sme" rel="noopener noreferrer" target="_blank"><img src="/sme.png" alt="sme" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.apps.MyXL" rel="noopener noreferrer" target="_blank"><img src="/xl.png" alt="xl" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.yamahareward" rel="noopener noreferrer" target="_blank"><img src="/yamaha.png" alt="yamaha" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.lawson" rel="noopener noreferrer" target="_blank"><img src="/lawson.webp" alt="lawson" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.burgerking" rel="noopener noreferrer" target="_blank"><img src="/burger_king.webp" alt="burger_king" width={48} height={48} /></Link>
                      </div>
                      <p className='mt-2'>
                        <em><b>Flutter, etc.</b></em>
                      </p>
                      <div className={`${styles["image-container"]}`}>
                        <Link href="https://play.google.com/store/apps/details?id=com.pea.peavolta" rel="noopener noreferrer" target="_blank"><img src="/pea_volta.webp" alt="pea_volta" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.cloudpos.stamp" rel="noopener noreferrer" target="_blank"><img src="/bzb_merchant.webp" alt="bzb_merchant" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.bzbs.buzzpos" rel="noopener noreferrer" target="_blank"><img src="/bzb_pos.webp" alt="bzb_pos" width={48} height={48} /></Link>
                        <Link href="https://play.google.com/store/apps/details?id=com.koithe.app.th" rel="noopener noreferrer" target="_blank"><img src="/koite.png" alt="koite" width={48} height={48} /></Link>
                      </div>
                    </div>

                    <div className={`${styles["resume-item1"]}`}>
                      <h4>Android Developer</h4>
                      <h5>Jan 2014 - May 2015</h5>
                      <p>
                        <em>Excel Australasia, Bangkok</em>
                      </p>
                      <ul className="list-disc">
                        <li>Analyse and planing to process a system.</li>
                        <li>Evaluation period to work</li>
                        <li>
                          Design and develop interactive, database-oriented UI,
                          UX Android.
                        </li>
                      </ul>
                      <p>
                        <em><b>Java + Kotlin</b></em>
                      </p>
                      <div className={`${styles["image-container"]}`}>
                        <img src="/eunic.png" alt="eunic" width={48} height={48} />
                        <img src="/thailand_exhibition.png" alt="thailand_exhibition" width={48} height={48} />
                        <img src="/tree_condo.webp" alt="tree_condo" width={48} height={48} />
                        <img src="/kaset_brand.png" alt="kaset_brand" width={48} height={48} />
                      </div>
                    </div>

                    <div className={`${styles["resume-item1"]}`}>
                      <h4>Android Developer</h4>
                      <h5>May 2013 - Jan 2014</h5>
                      <p>
                        <em>Devsense, Bangkok</em>
                      </p>
                      <ul className="list-disc">
                        <li>Manage and optimize all the mobile</li>
                      </ul>
                      <p>
                        <em><b>Java</b></em>
                      </p>
                      <div className={`${styles["image-container"]}`}>
                        <img src="/ruindy.webp" alt="ruindy" width={48} height={48} />
                        <img src="/watson_th.webp" alt="watson_th" width={48} height={48} />
                        <img src="/suraj_intergold.webp" alt="suraj_intergold" width={48} height={48} />
                        <img src="/aec.png" alt="aec" width={48} height={48} />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
